Small blog post on using grouping for result diversification
vespa-engine/blog pull request #122
Opened 2021-11-11 19:50 UTC by jobergum

Try to address questions on how to achieve result diversity with Vespa. 

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-11-11 19:59 UTC, jobergum commented
![image](https://user-images.githubusercontent.com/20928528/141361104-710f5bb0-4276-4932-896e-137b4a29f0f7.png)

2021-11-12 08:06 UTC, kkraune requested changes
Great post, a few comments!

2021-11-12 08:06 UTC, kkraune commented on _posts/2021-11-11-result-diversification-with-vespa.md
> +[Searcher grouping api](https://docs.vespa.ai/en/grouping.html#search-container-api)
```suggestion
[Searcher grouping api](https://docs.vespa.ai/en/grouping.html#search-container-api).
```

2021-11-12 08:06 UTC, kkraune commented on _posts/2021-11-11-result-diversification-with-vespa.md
> +- The total number of unique values the field can take.
```suggestion
- The total number of unique values in the field. 
```

2021-11-12 08:06 UTC, kkraune commented on _posts/2021-11-11-result-diversification-with-vespa.md
> +to which the query is fan out increases network bandwidth. The performance
```suggestion
to which the query is fanned out increases network bandwidth. The performance
```

2021-11-12 08:06 UTC, kkraune commented on _posts/2021-11-11-result-diversification-with-vespa.md
> +# Fine-tuning result diversification
As the blog post is about diversification, we should add a few more details here, like a more real-world example with some pseudo-code

2021-11-12 14:02 UTC, kkraune approved these changes
This is now a great post - ready to go with the minor fixes to punctuation!

2021-11-12 14:02 UTC, kkraune commented on _posts/2021-11-11-result-diversification-with-vespa.md
> +, using a document side quality attribute. The match phase degradation feature supports diversity criteria
```suggestion
feature, which sets an upper limit on the number of documents ranked,
using a document side quality attribute. The match phase degradation feature supports diversity criteria
```

2021-11-12 14:12 UTC, merged