Add mini-blog about sliced visiting
vespa-engine/blog pull request #123
Opened 2021-11-12 15:33 UTC by jonmv

@kkraune and @jobergum please review.

2021-11-12 17:50 UTC, jobergum requested changes
Great! I would change the title to something more catchy

Other
- rewrite MB/s to network units e.g Gbps 
- avoid us/we (Yes, I happen to do this as well)
- Some long sentences
-

2021-11-12 17:50 UTC, jobergum commented on _posts/2021-11-12-sliced-visiting.md
> +This short blog post shows how the new slicing feature lets
```suggestion
This blog post shows how the new slicing feature lets
```

2021-11-12 17:50 UTC, jobergum commented on _posts/2021-11-12-sliced-visiting.md
> +Vespa is built to scale; documents are automatically spread across any number of content nodes, and queries and document
```suggestion
Vespa is built to scale; documents are distributed across any number of content nodes, and queries and document
```

2021-11-12 17:50 UTC, jobergum commented on _posts/2021-11-12-sliced-visiting.md
> +## Experimental Throughput
```suggestion
## Experimental Throughput Benchmarking
```

2021-11-12 17:50 UTC, jobergum commented on _posts/2021-11-12-sliced-visiting.md
> +
```suggestion
# Summary
```

2021-11-12 17:50 UTC, jobergum commented on _posts/2021-11-12-sliced-visiting.md
> +containers and the number of clients used for visiting—whicheveris the bottleneck.
```suggestion
containers and the number of clients used for visiting, whichever is the bottleneck.
```

2021-11-12 17:50 UTC, jobergum commented on _posts/2021-11-12-sliced-visiting.md
> +optionally filtered by a [selection](https://docs.vespa.ai/en/reference/document-select-language.html), and sends these to
Hard to read this sentence, consider breaking it up.

2021-11-14 18:25 UTC, kkraune commented
great post! I think it would be much easier to understand if it had an illustration with multiple clients, container and content nodes, so you could see how the clients could use different container nodes to visit its subspace. maybe a link to https://docs.vespa.ai/en/content/buckets.html for details

also, the stream feature should be more prominent. it solves a different problem than slicing does, and should have its own section.

then it should all come together at the end, how the slicing adds throughput, and stream makes latency less of an issue, to achieve high read rates using multiple clients, over long distances (e.g. to support easy multizone setup, easy to transport the data using this)

2021-11-15 07:31 UTC, jonmv commented
In my mind, the stream part is a minor thing. Using more slices makes it less impactful, as you'll always have data to process at both ends, and then it's sort of just a prerequisite for slicing. Playing it down was on purpose, to keep the post as short as possible. I also hid the buckets on purpose, as slicing isn't necessarily tied to those—it just happens to be, but that's a detail. Knowing exactly how slicing works isn't necessary to appreciate it, in my opinion, and I prefer keeping things simpler, with a smaller scope, when possible. 
I was considering a figure, though. Will see if I can make one I'm happy with. 
Let's keep the discussion going if you think I'm wrong about the above points.

2021-11-15 07:41 UTC, kkraune commented
you are too modest :-) both slicing and streaming are means to achieve higher throughput, where streaming is the easiest once for the user, but less impactful, unless in the high-latency case. I will not insist, but I thought streaming is important enough for a more prominent position. lets have @jobergum be the tiebreaker ;-)

2021-11-15 07:42 UTC, jonmv commented
On second thought, a figure doesn't make that much sense either without the buckets being disjoint across content nodes, etc., either, as it'll just be a few clients hitting different containers.

2021-11-15 07:44 UTC, jonmv commented
Hmm, yes, it is a point that streamed responses are beneficial also when you don't want to use parallel clients, and slicing. So I tried to put it in a separate section at first, but wasn't happy with that, because I found it took too much (cognitive) space, since it also entails a description of continuation tokens, which again are needed because visits are stateless between HTTP calls, and so on. But I could make another attempt at this ...

2021-11-15 13:42 UTC, jonmv commented
PTAL.

2021-11-15 14:30 UTC, kkraune commented
Great! I like the illustration! and the text flow is much better. maybe just rename to today's date and ship it :-)

2021-11-15 14:30 UTC, kkraune approved these changes

2021-11-15 15:04 UTC, merged