Add text-image search blog
vespa-engine/blog pull request #127
Opened 2021-11-28 17:17 UTC by lesters

@kkraune @thigm85 Please review.

2021-11-29 10:47 UTC, jobergum approved these changes
Fantastic post. Unrelated to the content but @kkraune can we see if we can change the pink highlight of `stuff` ?

![image](https://user-images.githubusercontent.com/20928528/143854400-4593045d-ea64-406d-b05c-ce6a50fb4747.png)

2021-11-29 11:37 UTC, thigm85 requested changes

2021-11-29 11:37 UTC, thigm85 commented on _posts/2021-11-28-text-image-search.md
> +fine-tuned during this training.
AFAIK, the CLIP team decided to train their models from scratch. 

From page 4: "Due to the large size of our pre-training dataset, over-fitting
is not a major concern and the details of training CLIP are
simplified compared to the implementation of Zhang et al.
(2020). We train CLIP from scratch without initializing the
image encoder with ImageNet weights or the text encoder
with pre-trained weights."

2021-11-29 11:37 UTC, thigm85 commented on _posts/2021-11-28-text-image-search.md
> +look in the next section.
remove bit?

2021-11-29 12:35 UTC, lesters commented on _posts/2021-11-28-text-image-search.md
> +fine-tuned during this training.
Good catch!

2021-11-29 12:35 UTC, lesters commented on _posts/2021-11-28-text-image-search.md
> +look in the next section.
:+1:

2021-11-29 15:05 UTC, kkraune approved these changes
This is great, just minor commments

2021-11-29 15:05 UTC, kkraune commented on _posts/2021-11-28-text-image-search.md
> +### Pyvespa
should be consistent Pyvespa or PyVespa or pyvespa all over - I am not sure which is right ...

2021-11-29 15:07 UTC, kkraune commented
> Fantastic post. Unrelated to the content but @kkraune can we see if we can change the pink highlight of `stuff` ?
> 
> ![image](https://user-images.githubusercontent.com/20928528/143854400-4593045d-ea64-406d-b05c-ce6a50fb4747.png)

Agreed, this is is the out-of-the-box stylesheet, will look at alternatives (that will apply to all posts and - don't hold this one for this change)

2021-11-30 08:15 UTC, lesters commented on _posts/2021-11-28-text-image-search.md
> +    logits_per_image, logits_per_text = model(image, text)
No, this is correct. The `image_features` and `text_features` are there to point out that images and text are transformed to representations, but that is also done inside `model`. As such, it is not necessary here, but I mention them in the text below.

2021-11-30 08:18 UTC, lesters commented on _posts/2021-11-28-text-image-search.md
> +### Pyvespa
Changed it to `pyvespa` except when starting a sentence.

2021-11-30 08:22 UTC, merged